### ISSUE TITLE
[AttributeError: 'Qwen2Tokenizer' object has no attribute 'eod_id'] Can't finetune Qwen/Qwen1.5-0.5B-Chat

### ISSUE THREAD

**Issue by deltawi** [QwenLM/Qwen1.5#48]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

When you run with model `Qwen/Qwen1.5-0.5B-Chat`:
```bash
finetune/finetune_lora_single_gpu.sh
```

You get the error: 
```
Traceback (most recent call last):
  File "/Qwentuning/Qwen/finetune.py", line 374, in <module>
    train()
  File "/Qwentuning/Qwen/finetune.py", line 328, in train
    tokenizer.pad_token_id = tokenizer.eod_id
AttributeError: 'Qwen2Tokenizer' object has no attribute 'eod_id'
```

### 期望行为 | Expected Behavior

Should train the model

### 复现方法 | Steps To Reproduce

1. Linux environment
2. `pip install transformers peft deepspeed datasets`
3. Change the script `finetune/finetune_lora_single_gpu.sh` : model name to `Qwen/Qwen1.5-0.5B-Chat`
4. Change path for the data
5. Run the script with `finetune/finetune_lora_single_gpu.sh`

### 运行环境 | Environment

```Markdown
- OS: Linux
- Python: 3.10
- Transformers: 4.37.2
- PyTorch: 2.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.7
```

**Comment by jklj077** [comment]
Hi, we found that you were using Qwen(1.0) code to finetune Qwen1.5 models, which is incompatible. To finetune Qwen1.5 models, please refer to the README.

**Comment by deltawi** [comment]
I was able to make it work with the same script as 1.0 but adapted to 1.5, please advise if it's correct: 

- https://github.com/deltawi/Qwentuning/blob/main/finetune.py

**Comment by HuXinjing** [comment]
> Hi, we found that you were using Qwen(1.0) code to finetune Qwen1.5 models, which is incompatible. To finetune Qwen1.5 models, please refer to the README.

你好 请问直接添加特殊token可以吗 我看llamafactory好像是往tokenizer对象里加里特殊token？

**Comment by JustinLin610** [comment]
Check the latest finetuning script, or Llama factory, or Axolotl

**Comment by Xingxiangrui** [comment]
Hello, this format may not be compatible if you are using the Alpaca data format and Qwen's fine-tuning script together. If you are using the author's fine-tuning script, you need to use the JSON format provided by the author, as detailed in the readme.
```
[
  {
    "id": "identity_0",
    "conversations": [
      {
        "from": "user",
        "value": "你好"
      },
      {
        "from": "assistant",
        "value": "我是一个语言模型，我叫通义千问。"
      }
    ]
  }
]
```
